auth_code="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkubG9naW4uZnllcnMuaW4iLCJpYXQiOjE3MjU4ODU2MzksImV4cCI6MTcyNTkxNTYzOSwibmJmIjoxNzI1ODg1MDM5LCJhdWQiOiJbXCJ4OjBcIiwgXCJ4OjFcIiwgXCJkOjFcIiwgXCJ4OjBcIl0iLCJzdWIiOiJhdXRoX2NvZGUiLCJkaXNwbGF5X25hbWUiOiJYUDMzNjU5Iiwib21zIjoiSzEiLCJoc21fa2V5IjoiMWVlYzg2Y2E2YjZlMjExZWRiYTZlMWM0NWJiMjIzMTYzNDQxMzcyODFlODQzNzUxZjJiNWNjNWMiLCJub25jZSI6IiIsImFwcF9pZCI6IkdXSVlRWFlEVUkiLCJ1dWlkIjoiYTM2ZTI0OWM0YmQ4NGNjZmE0MDgzNWM2ZDg5NzkxZjciLCJpcEFkZHIiOiIwLjAuMC4wIiwic2NvcGUiOiIifQ.wjq8n46BeCbJ4pvWBSzTrPP2WdPqv8CJCgVbIXggkBM"
from fyers_apiv3 import fyersModel

client_id = "GWIYQXYDUI-100"
secret_key = "ZS0R3TLDZN"
redirect_uri = "http://127.0.0.1:5173/"
response_type = "code"  
state = "sample_state"
grant_type = "authorization_code"  


session = fyersModel.SessionModel(
    client_id=client_id,
    secret_key=secret_key,
    redirect_uri=redirect_uri,
    response_type=response_type,
    grant_type = "authorization_code"  
)

session.set_token(auth_code)
token = session.generate_token()
print(token)

kk = {'s': 'ok', 
 'code': 200, 
 'message': '', 
 'access_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE3MjU4ODU4OTEsImV4cCI6MTcyNTkyODI1MSwibmJmIjoxNzI1ODg1ODkxLCJhdWQiOlsieDowIiwieDoxIiwiZDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCbTN1M0RMdG8zXzl5Q3Ftc3duWVVvb3FDZ3JyUTFnQUV2bkI1NEtDNlpjYzZRSWdHR1BwdmFSbUtjYWlsSUFIYTJoYm5BWjFIMkxWY0pkNWNjLVVDVEgyTU8wVkdqcUJ5NTRmQVJoYjJMVmJuYkFpUT0iLCJkaXNwbGF5X25hbWUiOiJQUkFTQU5OQSBCSVNFTiIsIm9tcyI6IksxIiwiaHNtX2tleSI6IjFlZWM4NmNhNmI2ZTIxMWVkYmE2ZTFjNDViYjIyMzE2MzQ0MTM3MjgxZTg0Mzc1MWYyYjVjYzVjIiwiZnlfaWQiOiJYUDMzNjU5IiwiYXBwVHlwZSI6MTAwLCJwb2FfZmxhZyI6Ik4ifQ.WBrXx-eaTHGUzNm8Z_Og7Q7Qj20efuDvLp6IyWcyTuk', 
 'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE3MjU4ODU4OTEsImV4cCI6MTcyNzEzNzg1MSwibmJmIjoxNzI1ODg1ODkxLCJhdWQiOlsieDowIiwieDoxIiwiZDoxIiwieDowIl0sInN1YiI6InJlZnJlc2hfdG9rZW4iLCJhdF9oYXNoIjoiZ0FBQUFBQm0zdTNETHRvM185eUNxbXN3bllVb29xQ2dyclExZ0FFdm5CNTRLQzZaY2M2UUlnR0dQcHZhUm1LY2FpbElBSGEyaGJuQVoxSDJMVmNKZDVjYy1VQ1RIMk1PMFZHanFCeTU0ZkFSaGIyTFZibmJBaVE9IiwiZGlzcGxheV9uYW1lIjoiUFJBU0FOTkEgQklTRU4iLCJvbXMiOiJLMSIsImhzbV9rZXkiOiIxZWVjODZjYTZiNmUyMTFlZGJhNmUxYzQ1YmIyMjMxNjM0NDEzNzI4MWU4NDM3NTFmMmI1Y2M1YyIsImZ5X2lkIjoiWFAzMzY1OSIsImFwcFR5cGUiOjEwMCwicG9hX2ZsYWciOiJOIn0.-Dnlji5q7RxWg26bPNeCMgPXd837LZ-tBCp3g1GuPMg'
 }